### ISSUE TITLE
The question of the weights pre-trained on the AffectNet-7 datasets

### ISSUE THREAD

**Issue by NKBpower** [MSA-LMC/S2D#10]
Hello, I have a questions for you about the experimental details of your article, because you said "For the DFER model, we initialized it with the weights pre-trained on the AffectNet-7 dataset and fine-tuned it on the DFER dataset.“ In this part, I would like to ask whether the weights refers to the weights of the model for MAE operations or the weights of the model after training on the AffectNet-7 dataset?

**Comment by cyinen** [comment]
The weights here refer the model fine-tuned on the AffectNet-7 dataset.

**Comment by NKBpower** [comment]
Okay, thanks for your answer, I solved this question when I re-read this article later, thank you very much for your reply to this question

**Comment by NKBpower** [comment]
Okay, thanks for your answer, I solved this question when I re-read this article later, thank you very much for your reply to this question.
