### ISSUE TITLE
SFER model

### ISSUE THREAD

**Issue by s25813s5** [MSA-LMC/S2D#11]
HI,
Could you  provide the SFER model for Pretrain-AffectNet-7.pth?

**Comment by cyinen** [comment]
You can found the model from this [link](https://drive.google.com/file/d/1Y9zz8z_LwUi-tSFBAwDPZkVoyY6mhZlu/view)

**Comment by s25813s5** [comment]
Sorry, I meant the ViT model architecture trained on AffectNet. 
I want to reproduce the performance of Pretrain-AffectNet-7.pth on the AffectNet dataset.

**Comment by cyinen** [comment]
You can obtain the SFER model by removing the temporal module.

**Comment by s25813s5** [comment]
The classifier part seems to be different as well. Could you offer the classification parts of head and weak_head?
