### ISSUE TITLE
Error when running bash run.sh after downloading pre-trained weights

### ISSUE THREAD

**Issue by rezabrgi** [MSA-LMC/S2D#12]
Hello,

I downloaded the pre-trained model weights in ZIP format, but I did not extract the files because the file extension is lost upon extraction. Instead, I created a folder named ckpts and placed the ZIP file inside this folder. After completing the setup, I ran the bash run.sh script, but encountered the following error:

(s2d) reza@reza-virtual-machine:~/S2D-main$ bash run.sh
cp: cannot stat 'ft_dfew.sh': No such file or directory
./saved/model/finetuning/dfew/affectnet7/ckpts/Pretrain-AffectNet-7.pth/split01_eval_lr_1e-5_epoch_100_Augment_size224_sr1#tag#affectnet_pretrain ckpts/Pretrain-AffectNet-7.pth
cp: cannot stat 'ft_dfew.sh': No such file or directory
./saved/model/finetuning/dfew/affectnet7/ckpts/Pretrain-AffectNet-7.pth/split02_eval_lr_1e-5_epoch_100_Augment_size224_sr1#tag#affectnet_pretrain ckpts/Pretrain-AffectNet-7.pth
cp: cannot stat 'ft_dfew.sh': No such file or directory
./saved/model/finetuning/dfew/affectnet7/ckpts/Pretrain-AffectNet-7.pth/split03_eval_lr_1e-5_epoch_100_Augment_size224_sr1#tag#affectnet_pretrain ckpts/Pretrain-AffectNet-7.pth
cp: cannot stat 'ft_dfew.sh': No such file or directory
./saved/model/finetuning/dfew/affectnet7/ckpts/Pretrain-AffectNet-7.pth/split04_eval_lr_1e-5_epoch_100_Augment_size224_sr1#tag#affectnet_pretrain ckpts/Pretrain-AffectNet-7.pth
cp: cannot stat 'ft_dfew.sh': No such file or directory
./saved/model/finetuning/dfew/affectnet7/ckpts/Pretrain-AffectNet-7.pth/split05_eval_lr_1e-5_epoch_100_Augment_size224_sr1#tag#affectnet_pretrain ckpts/Pretrain-AffectNet-7.pth
done!
cp: cannot stat 'ft_ferv39k.sh': No such file or directory
./saved/model/finetuning/ferv39k/affectnet7+VoxCeleb2/ckpts/Pretrain-AffectNet-7.pth/eval_lr_1e-5_epoch_100_Augment_size224_sr1#tag#affectnet_pretrain ckpts/Pretrain-AffectNet-7.pth
done!
ckpts/Pretrain-AffectNet-7.pth ./saved/model/finetuning/mafw/affectnet7+VoxCeleb2/ckpts/Pretrain-AffectNet-7.pth/split01_eval_lr_1e-5_epoch_100_Augment_size224_sr1#tag#affectnet_pretrain 1
Done!
ckpts/Pretrain-AffectNet-7.pth ./saved/model/finetuning/mafw/affectnet7+VoxCeleb2/ckpts/Pretrain-AffectNet-7.pth/split02_eval_lr_1e-5_epoch_100_Augment_size224_sr1#tag#affectnet_pretrain 2
Done!
ckpts/Pretrain-AffectNet-7.pth ./saved/model/finetuning/mafw/affectnet7+VoxCeleb2/ckpts/Pretrain-AffectNet-7.pth/split03_eval_lr_1e-5_epoch_100_Augment_size224_sr1#tag#affectnet_pretrain 3
Done!
ckpts/Pretrain-AffectNet-7.pth ./saved/model/finetuning/mafw/affectnet7+VoxCeleb2/ckpts/Pretrain-AffectNet-7.pth/split04_eval_lr_1e-5_epoch_100_Augment_size224_sr1#tag#affectnet_pretrain 4
Done!
ckpts/Pretrain-AffectNet-7.pth ./saved/model/finetuning/mafw/affectnet7+VoxCeleb2/ckpts/Pretrain-AffectNet-7.pth/split05_eval_lr_1e-5_epoch_100_Augment_size224_sr1#tag#affectnet_pretrain 5
Done!

I am running this on an Ubuntu 64-bit virtual machine. Could you please assist me with troubleshooting this issue? Specifically, I would like to know if the pre-trained weights need to be extracted or if there are any other steps I need to follow.

Thank you!

**Comment by cyinen** [comment]
1.  Please check the output file  and provide more outputs.
2. You can download the pre-trained model with .pth extension directly.

**Comment by rezabrgi** [comment]
![Screenshot from 2024-11-27 02-40-15](https://github.com/user-attachments/assets/eef091a2-9f37-433b-99fa-c487fe50a6b8)

**Comment by cyinen** [comment]
Please check the nohup.out file in the 'saved' directory

**Comment by rezabrgi** [comment]
The issue has been resolved by replacing the following two phrases in the ft_dfew.sh file:

Original Phrase: cp "$(basename "$0")" $OUTPUT_DIR/

new phrase:    cp "$(dirname "${BASH_SOURCE[0]}")/$(basename "$0")" $OUTPUT_DIR/
