### ISSUE TITLE
mobilefacenet resolution

### ISSUE THREAD

**Issue by MyungBeomHer** [MSA-LMC/S2D#3]
Hi! Thank you for your amazing work. I want to ask you a question of your resolution in mobilefacenet.
I knew that CNN-based performance changes as resolution changes. For example, if learning is done at 112 * 112 resolution, then when finetuning at 224 * 224 resolution, performance deteriorates due to the fixed size of the kernel. Your landmark detector, mobilefacenet, was trained on the landmark task at 112 * 112 resolution and then frozen. But when finetuning at 224 * 224 resolution, is there any performance degradation even when used as a landmark detector?

**Comment by cyinen** [comment]
Thanks for your question! We have resized the image to 112x112 befor extracting landmark-aware features.
