### ISSUE TITLE
problems about pre-trained weights

### ISSUE THREAD

**Issue by GJandy** [MSA-LMC/S2D#5]
Can you offer the google drive link for pre-trained weights ? not baidu link.

**Comment by cyinen** [comment]
It can be found here [google drive](https://drive.google.com/file/d/1Y9zz8z_LwUi-tSFBAwDPZkVoyY6mhZlu/view?usp=drive_link)

**Comment by GJandy** [comment]
@cyinen I have send a request for google drive

**Comment by cyinen** [comment]
I have updated it, thank you !
