### ISSUE TITLE
fine-tuned checkpoints google drive link

### ISSUE THREAD

**Issue by varshapendyala** [MSA-LMC/S2D#8]
Hello,

Could you please share the google drive link of all the fine-tuned checkpoints since the university server does not allow downloads from baidu. Thanks!

**Comment by cyinen** [comment]
Since the fine-tuning weights are too large, there isn’t enough space on Google Drive, so I stored them on the onedrive, you can download from here [ondedrive](https://mailhfuteducn-my.sharepoint.com/personal/2022111029_mail_hfut_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2F2022111029%5Fmail%5Fhfut%5Fedu%5Fcn%2FDocuments%2Fresearch%2F论文开源代码%2FS2D%2Dgithub)

**Comment by varshapendyala** [comment]
> Since the fine-tuned weights are too large, there isn’t enough space on my Google Drive, so I stored them on the onedrive, you can download from here [one drive](https://mailhfuteducn-my.sharepoint.com/personal/2022111029_mail_hfut_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2F2022111029%5Fmail%5Fhfut%5Fedu%5Fcn%2FDocuments%2Fresearch%2F%E8%AE%BA%E6%96%87%E5%BC%80%E6%BA%90%E4%BB%A3%E7%A0%81%2FS2D%2Dgithub)

Hey, I get the following warning:
"Sorry, [my email] was not found in the mailhfuteducn-my.sharepoint.com directory . Please try again later while we attempt to automatically fix this problem for you."

Looks like I do not have access to it..could you please fix this.

**Comment by cyinen** [comment]
Please try again with this [link](https://mailhfuteducn-my.sharepoint.com/:f:/g/personal/2022111029_mail_hfut_edu_cn/EgKQNq8Y2chKl2TSoYf_OA0BQpCwx-FDw2ksPaMxBntZ8A)

**Comment by varshapendyala** [comment]
> Please try again with this [link](https://mailhfuteducn-my.sharepoint.com/:f:/g/personal/2022111029_mail_hfut_edu_cn/EgKQNq8Y2chKl2TSoYf_OA0BQpCwx-FDw2ksPaMxBntZ8A)

this link worked, thanks a lot!
